version: '3.8'

services:
  server:
    container_name: server
    build:
      context: /home/ec2-user/WeMo
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_DATABASE: ${DATABASE_NAME}
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - webnet
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
    driver: local
networks:
  webnet:
    driver: bridge
